### ISSUE TITLE
HR should be able to view & edit training program details

### ISSUE THREAD

**Issue by copypastedeveloper** [ThePiratesofSiliconValley/Orientation-Api#39]
**Given** user is viewing the list of training programs
**When** the user clicks on a training program
**Then** the user should see all details of that training program
**And** any employees that are currently attending the program

**Given** user is viewing the details of a training program
**When** the user clicks on the edit link
**Then** the user should be presented with a form that allows the user to edit any property of the training program **unless** the training program has already taken place

**Comment by daviddassau** [comment]
- [x] Adjust form to add `View Details` button.
- [x] Add `Details` column to `TrainingPrograms` table in SQL.
- [x] In Repo, in the post function, add in the respective column that you just added to the `TrainingPrograms` table.
- [x] Add `Details` to the `TrainingProgramDto.cs`.

**Comment by daviddassau** [comment]
### Training Program Details Page | Boilerplate Setup
- [x] Create Training Program Details partial.
- [x] Create Training Program Details controller.
- [x] Add both to `app.js`.
- [x] Write message to make sure that everything is working correctly.

**Comment by daviddassau** [comment]
### Click Event for View Details Button on Trainings Page
- [x] This button, when clicked, should route to the `TrainingProgramDetails.html` partial.
- [x] Info from that particular training should display on the page.
